name =input ("请输入您的名字")
age = int(input("请输入您的年龄"))
sexxy = input("请输入您的性别")
high = float(input("请输入您的身高"))
weight = float(input("请输入体重"))
ID_number = int(input("请输入你的身份证号"))
education =input("请输入你的学历")
birthdat = input("请输入你的出生年月")
amazy = input("请输入你老婆的名字")
addr = input ("请输入你的家庭住址")
tel = int(input("请输入你的家庭电话"))
case = input("请输入职位")
money = int(input("请输入薪水"))
print("职位%s\nmonty%d\n身高%f\n"%(case,noey,high))

